export enum ColumnType {
    BIT = "bit",
    INT = "int",
    TINY_INT = "tinyint",
    SMALL_INT = "smallint",
    MEDIUM_INT = "mediumint",
    BIG_INT = "bigint",
    FLOAT = "float",
    DOUBLE = "double",
    DECIMAL = "decimal",
    BOOLEAN = "boolean",
    DATE = "date",
    DATETIME = "datetime",
    TIME = "time",
    YEAR = "year",
    CHAR = "char",
    N_CHAR = "nchar",
    VARCHAR = "varchar",
    TEXT = "text",
    BLOB = "blob",
    ENUM = "enum",
    JSON = "json",
}
